name: Build RACE EXE for Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Clean Electron Builder Cache
      run: |
        Remove-Item "$env:LOCALAPPDATA\electron-builder\cache" -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item "$env:USERPROFILE\.cache\electron-builder" -Force -Recurse -ErrorAction SilentlyContinue
      shell: powershell

    - name: Build Windows EXE
      # Uses the CLI flag to force skipping publishing
      run: npm run dist -- --publish never

    - name: Upload EXE Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RACE-Windows-Installer
        path: dist/*.exe
